import type { SessionData } from "../types";

export const MOCK_SESSIONS: SessionData[] = [
    {
        id: "mock-main-direct",
        key: "agent:main:main",
        sub: "whatsapp:g-agent-main-main",
        label: "",
        kind: "direct",
        status: "active",
        msgs: 120,
        lastActive: "49m ago",
        updated: "49m ago",
        tokens: "75010 / 272000",
    },
    {
        id: "mock-main-group-1",
        key: "agent:main:telegram:group:-1003889990005",
        sub: "telegram:g-my-agents",
        label: "",
        kind: "group",
        status: "idle",
        msgs: 84,
        lastActive: "6d ago",
        updated: "6d ago",
        tokens: "68919 / 272000",
    },
    {
        id: "mock-main-group-2",
        key: "agent:main:whatsapp:group:120363...",
        sub: "whatsapp:g-my-agents-wa",
        label: "",
        kind: "group",
        status: "idle",
        msgs: 0,
        lastActive: "6d ago",
        updated: "6d ago",
        tokens: "n/a",
    },
    {
        id: "mock-rysha-direct",
        key: "agent:rysha:main",
        sub: "",
        label: "",
        kind: "direct",
        status: "idle",
        msgs: 31,
        lastActive: "7d ago",
        updated: "7d ago",
        tokens: "19513 / 200000",
    },
];
